### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by djsaunde** [fomorians/pyoneer#31]
`pip install pyoneer` and then `python -c "import pyoneer"` gives:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyoneer'
```

This is on Ubuntu 18.04.

**Comment by jimfleming** [comment]
It's not published on pypi.org yet. We should do that soon.

**Comment by jimfleming** [comment]
The package is now published on pypi: https://pypi.org/project/fomoro-pyoneer/

    pipenv install fomoro-pyoneer
